version: "3.9"
   
services:
  web:
    build: .
    command: python vulnerable_website/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - LOCAL=1
    depends_on:
      - migration
  migration:
    build: .
    command: python vulnerable_website/manage.py migrate
    volumes:
      - .:/code
    environment:
      - LOCAL=1