version: "3.9"
   
services:
  vulnerable_website:
    build: ./vulnerable_website
    command: python vulnerable_website/manage.py runserver 0.0.0.0:1234
    volumes:
      - .:/code
    ports:
      - "1234:1234"
    environment:
      - LOCAL=1
    depends_on:
      - migration_vulnerable_website
  migration_vulnerable_website:
    build: ./vulnerable_website
    command: python vulnerable_website/manage.py migrate
    volumes:
      - .:/code
    environment:
      - LOCAL=1
  malicious_website:
    build: ./malicious_website
    command: python malicious_website/manage.py runserver 0.0.0.0:5678
    volumes:
      - .:/code
    ports:
      - "5678:5678"
    environment:
      - LOCAL=1
  reverse_proxy:
    build: ./reverse_proxy
    ports:
      - "80:80"
